WebRaoVat/WebRaoVat/Models/Post.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.PostImages = new HashSet<PostImage>();
        }
    
        public int PostId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Title { get; set; }
        public string TitleAlias { get; set; }
        public int CategoryId { get; set; }
        public string ShortDescription { get; set; }
        public string Detail { get; set; }
        public string Price { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<byte> PostType { get; set; }
        public Nullable<int> HitCount { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual PostCategory PostCategory { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ICollection<PostImage> PostImages { get; set; }
    }
}

WebRaoVat/WebRaoVat/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using WebRaoVat.Filters;
using WebRaoVat.Models;

namespace WebRaoVat.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class PostController : Controller
    {
        private raovat_dbEntities db = new raovat_dbEntities();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index(int CatId = 0,int page = 1, int PageSize = 5, int SortBy = 1, bool IsAsc = true, string Search = null)
        {
            if (CatId != 0) // user want to view specific category's post
                return RedirectToAction("PostCategory", "Details", new { CatId = CatId });

          /*  var posts = db.Posts.Include(p => p.PostCategory).Include(p => p.UserProfile).Include(p => p.Zone);*/
            //tim kiem post
            var posts = db.Posts.Where(
                                    p => Search == null
                                    || p.Title.Contains(Search)
                                    || p.ShortDescription.Contains(Search)
                                    || p.Detail.Contains(Search)
                                    || p.TitleAlias.Contains(Search));
            posts = posts.Where(p => p.Approved == true);
            IEnumerable<Post> postlist;
            switch (SortBy)
            {
                case 1:
                    postlist = IsAsc ? posts.OrderBy(p => p.Title) : posts.OrderByDescending(p => p.Title);
                    break;
                case 2:
                    postlist = IsAsc ? posts.OrderBy(p => p.Created) : posts.OrderByDescending(p => p.Created);
                    break;
                case 3:
                    postlist = IsAsc ? posts.OrderBy(p => p.HitCount) : posts.OrderByDescending(p => p.HitCount);
                    break;
                case 4:
                    postlist = IsAsc ? posts.OrderBy(p => p.Price) : posts.OrderByDescending(p => p.Price);
                    break;
                default:
                    postlist = IsAsc ? posts.OrderBy(p => p.PostId) : posts.OrderByDescending(p => p.PostId);
                    break;
            }
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = PageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((double)postlist.Count() / PageSize);
            ViewBag.SortBy = SortBy;
            ViewBag.IsAsc = IsAsc;
            ViewBag.Search = Search;
            postlist = postlist.Skip((page - 1) * PageSize).Take(PageSize).ToList();
            return View(postlist.ToList());
        }

        //
        // GET: /Post/PostManager
        public ActionResult PostManager(string Search, string UserName, string Category, string Zone, string IsActive, string PostType, string Approved, string Expired)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 100)
            {
                var CategoryLst = new List<string>();
                var ZoneLst = new List<string>();
                var PostTypeLst = new List<string>();
                var IsActiveLst = new List<string>();
                var ExpiredLst = new List<string>();
                var ApprovedLst = new List<string>();

                var CategoryQry = from d in db.PostCategories
                                  select d.CategoryName;
                var ZoneQry = from d in db.Zones
                                  select d.ZoneName;

                PostTypeLst.Add("All");
                PostTypeLst.Add("Tin Vip");
                PostTypeLst.Add("Tin Thuong");

                ExpiredLst.Add("All");
                ExpiredLst.Add("Hết Hạn");
                ExpiredLst.Add("Còn Hạn");

                CategoryLst.Add("All");
                CategoryLst.AddRange(CategoryQry.Distinct());
                ZoneLst.Add("All");
                ZoneLst.AddRange(ZoneQry.Distinct());

                ApprovedLst.Add("All");
                ApprovedLst.Add("Chưa kiểm duyệt");
                ApprovedLst.Add("Đã kiểm duyệt");

                IsActiveLst.Add("All");
                IsActiveLst.Add("Đang Hiển Thị");
                IsActiveLst.Add("Đang Ẩn");
            
                ViewBag.Category = new SelectList(CategoryLst, Category);
                ViewBag.Zone = new SelectList(ZoneLst, Zone);
                ViewBag.PostType = new SelectList(PostTypeLst, PostType);
                ViewBag.IsActive = new SelectList(IsActiveLst, IsActive);
                ViewBag.Expired = new SelectList(ExpiredLst, Expired);
                ViewBag.Approved = new SelectList(ApprovedLst, Approved);
                ViewBag.searchstring = Search;
                ViewBag.UserName = UserName;

                var post = db.Posts.Include(p => p.PostCategory);
                if (!String.IsNullOrEmpty(UserName))
                    post = post.Where(a => a.UserProfile.UserName.Contains(UserName));
                if (!String.IsNullOrEmpty(Search))
                    post = post.Where(a => a.Detail.Contains(Search)
                                        || a.ShortDescription.Contains(Search)
                                        || a.Title.Contains(Search)
                                        || a.TitleAlias.Contains(Search)
                                     );
                if (!String.IsNullOrEmpty(Category) && Category != "All")
                    post = post.Where(a => a.PostCategory.CategoryName == Category);
                if (!String.IsNullOrEmpty(Zone) && Zone != "All")
                    post = post.Where(a => a.Zone.ZoneName == Zone);
                if (!String.IsNullOrEmpty(Approved) && Approved != "All")
                {
                    post = post.Where(a => a.Approved == ((Approved == "Đã kiểm duyệt") ? true : false));
                }
                if (!String.IsNullOrEmpty(PostType) && PostType != "All")
                {
                    if (PostType == "Tin Vip")
                        post = post.Where(a => a.PostType == 1);
                    else
                        post = post.Where(a => a.PostType == 0);
                }
                if (!String.IsNullOrEmpty(IsActive) && IsActive != "All")
                {
                    post = post.Where(a => a.Active == ((IsActive == "Đang Hiển Thị") ? true : false));
                }

                if (!String.IsNullOrEmpty(Expired) && Expired != "All")
                {
                    if (Expired == "Còn Hạn")
                        post = post.Where(a => a.ExpireDate.Value < DateTime.Now);
                    else
                        post = post.Where(a => a.ExpireDate.Value > DateTime.Now);
                }

                return View(post.ToList());
            }
            else return HttpNotFound();
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            
            Post post = db.Posts.Find(id);
            
            if (post == null)
            {
                return HttpNotFound();
            }
            if ((WebSecurity.CurrentUserId == post.UserId) || (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 100))
                ViewBag.Editable = 1;
            else
                ViewBag.Editable = 0;
            db.Entry(post).State = EntityState.Modified;
            post.HitCount = ((post.HitCount != null) ? post.HitCount + 1 : 1);
            db.SaveChanges();

            ViewBag.Bookmarked = 0;
            if (WebSecurity.CurrentUserId > 0)
            {
                var temp = db.Bookmarks.Where(u => u.UserId == WebSecurity.CurrentUserId);
                if (temp.Where(u => u.PostId == id).Count() != 0)
                {
                    ViewBag.Bookmarked = 1;
                    ViewBag.BookmarkId = temp.Where(u => u.PostId == id).First().BookmarkId;
                }
            }
            var Ads = db.PostAds.Where(p => p.CategoryId == post.CategoryId);
            Ads = Ads.Where(p => p.ExpireDate > DateTime.Now);
            ViewBag.PostAds = null;
            if (Ads != null)
            {
                ViewBag.PostAds = Ads.OrderBy(p => p.ImageOdr).ToList();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.PostCategories, "CategoryId", "CategoryName");
            ViewBag.UserId = WebSecurity.CurrentUserId;
            ViewBag.ZoneId = new SelectList(db.Zones, "ZoneId", "ZoneName");
            ViewBag.ShortDescription = "";
            ViewBag.Detail = "";
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
          string[] images_links=null;
          if (Request["images"] != null)
             images_links = Request["images"].ToString().Split(':');

           if (ModelState.IsValid)
            {
                //first link is thumbnail;
                if (!String.IsNullOrEmpty(images_links[0]))
                    post.Thumbnail = images_links[0];
                else
                    post.Thumbnail = "NoImage.jpg";
                if (images_links.Length == 1 || String.IsNullOrEmpty(images_links[1]))
                {
                    images_links = new string[2];
                    images_links[1] = "NoImage.jpg";
                }                
                post.TitleAlias = "sample-alias"; //processing alias here
                post.Created = System.DateTime.Now;
                post.Active = true;
                post.Approved = false;
                post.ExpireDate = DateTime.Now.AddMonths(1);

WebRaoVat/WebRaoVat/Views/Post/Create.cshtml
@model WebRaoVat.Models.Post

@{
    ViewBag.Title = "Create";
}

<script src="/Scripts/nicEdit.js" type="text/javascript"></script>
<script type="text/javascript">
bkLib.onDomLoaded(function() {
    new nicEditor({fullPanel : true, iconsPath: '/Content/Images/nicEditorIcons.gif' }).panelInstance('Detail');
});
</script>

<fieldset>
<legend style="font-size:150%">Đăng tin rao vặt</legend>

<form action="/post/create" class="aspform" method="post" id="createform" name="createform" novalidate="novalidate">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="editor-field">
            <input type="hidden" name="UserId" value="@ViewBag.UserId" />
        </div>

        <br /> Tiêu đề tin<br />
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Title, new { maxlength="200" })
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <br /> Thể loại<br />
        <div class="editor-field">
            @Html.DropDownList("CategoryId")
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>
            
        <br /> Mô tả ngắn gọn<br />
        <textarea id="ShortDescription" name="ShortDescription" form="createform" rows="4" cols="60" maxlength="200">@ViewBag.ShortDescription</textarea>
				<br />
       <br /> Mô tả chi tiết<br />
       <textarea  id="Detail" name="Detail" form="createform" rows="20" cols="60" maxlength="2000">@ViewBag.Detail</textarea>

        <br /> Giá<br />
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Price, new { maxlength="20" })
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <br /> Quận/Huyện<br />
        <div class="editor-field">
            @Html.DropDownList("ZoneId")
            @Html.ValidationMessageFor(model => model.ZoneId)
        </div>
				
        <br /> Loại tin post:<br />
    @*      <div class="editor-field">
            @Html.EditorFor(model => model.PostType)
            @Html.ValidationMessageFor(model => model.PostType)
        </div>
    *@
    <div class="editor-field">
            <select name="PostType" id ="PostType">
               <option value="0">Bình Thường</option>
               <option value="1">Vip</option>
            </select>
        </div>
				
				<br />
        <p>
            <input type="submit" value="Đăng Tin" />
        </p>
</form>

<form action="/File/Upload" class ="dropzone" id="UploadImage">
        <h3>Chọn upload theo thứ tự:</h3>
		<ul>
		<li>Ảnh đại diện cho bài viết</li>
		<li>Ảnh sản phẩm 1</li>
		<li>Ảnh sản phẩm 2</li>
		<li>...(Tối đa 1 ảnh đại diện và 5 ảnh sản phẩm)</li>
		</ul>
</form>
	
            @{
        //        string[] fields = { "ThumbnailUrl", "PreviewImage1", "PreviewImage2", "PreviewImage3", "PreviewImage4", "PreviewImage5" };
                string form_id = "UploadImage";
                string form_contain_fields_id = "createform";
                int num_images = 6;
            }
    @if (ViewBag.Images != null)
    {
        @ViewsUtilities.EditFile(form_id, form_contain_fields_id, num_images, ViewBag.Images);
    }
    else
    {
        @ViewsUtilities.Upload_File(form_id, form_contain_fields_id, num_images);
    }
    
</fieldset>

<div class="preview-content">
    @ViewBag.HtmlContent
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebRaoVat/WebRaoVat/Views/Post/Delete.cshtml
@model WebRaoVat.Models.Post

<h2>Xóa</h2>

<h3>Bạn có chắc là sẽ xóa tin đăng này?</h3>
<fieldset>
    <legend>Tin Đăng</legend>

    <div class="display-field">
        @Html.HiddenFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.HiddenFor(model => model.Created)
    </div>

    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.TitleAlias)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.PostCategory.CategoryName)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.ShortDescription)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.Detail)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.Price)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.Zone.ZoneName)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.Active)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.PostType)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.HitCount)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.Thumbnail)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.Approved)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.ExpireDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Xóa" /> |
        @Html.ActionLink("Trở lại", "Index")
    </p>
}

WebRaoVat/WebRaoVat/Views/Post/Index.cshtml
@model IEnumerable<WebRaoVat.Models.Post>
@* function tao link cho viec sap xep tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper sortLink(string name, int id)
{  
  @* <a href="@Url.Action("Index", "Post", new { CatId= ViewBag.CatId, SortBy = id, PageSize= ViewBag.PageSize,Search=ViewBag.Search, IsAsc = (id == ViewBag.SortBy ? !@ViewBag.IsAsc : @ViewBag.IsAsc).ToString().ToLower() })">@name</a> *@
  @:  <option value="/Post/?CatId=@ViewBag.CatId&SorBy=@id&PageSize=@ViewBag.PageSize&Search=@ViewBag.Search&IsAsc=@((id == ViewBag.SortBy ? !@ViewBag.IsAsc : @ViewBag.IsAsc).ToString().ToLower())">@name</option>
}
@* function tao link cho viec phan trang, tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper buildLinks(int start, int end, string innerContent)
{
     for (int i = start; i <= end; i++)
     {
         <a class="@(i == ViewBag.CurrentPage ? "current" : "")" href="@Url.Action("Index", "Post", new { SortBy =ViewBag.SortBy, PageSize= ViewBag.PageSize, IsAsc=ViewBag.IsAsc, Search=ViewBag.Search ,page = i })">@(innerContent ?? i.ToString())</a>  
     }
     
}
@* function hien thi pagelink hop ly khi co qua nhieu trang vd 1.....5.current.7....100, tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper pageLinks()
{  
    const int maxPages = 11;
     
    if (ViewBag.TotalPages <= maxPages)
    {
        @buildLinks(1, (int)ViewBag.TotalPages, null)
        return;
    }
 
    int pagesAfter = ViewBag.TotalPages - ViewBag.CurrentPage; // Number of pages after current
    int pagesBefore = ViewBag.CurrentPage - 1; // Number of pages before current
 
    if (pagesAfter <= 4)
    {
        @buildLinks(1, 1, null) // Show 1st page
 
        int pageSubset = ViewBag.TotalPages - maxPages - 1 > 1 ? ViewBag.TotalPages - maxPages - 1 : 2;
        @buildLinks(pageSubset, pageSubset, "...") // Show page subset (...)
 
        @buildLinks(ViewBag.TotalPages - maxPages + 3, ViewBag.TotalPages, null) // Show last pages
 
        return; // Exit
    }
 
    if (pagesBefore <= 4)
    {
       @buildLinks(1, maxPages - 2, null) // Show 1st pages
 
 
       int pageSubset = maxPages + 2 < ViewBag.TotalPages ? maxPages + 2 : ViewBag.TotalPages - 1;
       @buildLinks(pageSubset, pageSubset, "...") // Show page subset (...)
 
       @buildLinks(ViewBag.TotalPages, ViewBag.TotalPages, null) // Show last page
 
        return; // Exit
 
    }
 
    if (pagesAfter > 4)
    {
        @buildLinks(1, 1, null) // Show 1st pages
 
        int pageSubset1 = ViewBag.CurrentPage - 7 > 1 ? ViewBag.CurrentPage - 7 : 2;
        int pageSubset2 = ViewBag.CurrentPage + 7 < ViewBag.TotalPages ? ViewBag.CurrentPage + 7 : ViewBag.TotalPages - 1;
 
        @buildLinks(pageSubset1, pageSubset1, pageSubset1 == ViewBag.CurrentPage - 4 ? null : "...") // Show 1st page subset (...)
 
        @buildLinks(ViewBag.CurrentPage - 3, ViewBag.CurrentPage + 3, null) // Show middle pages
         // Show 2nd page subset (...)
        // only show ... if page is contigous to the previous one.
        @buildLinks(pageSubset2, pageSubset2, pageSubset2 ==  ViewBag.CurrentPage + 4 ? null : "...")
        @buildLinks(ViewBag.TotalPages, ViewBag.TotalPages, null) // Show last page
         return; // Exit
 
    }    
}


@{
    ViewBag.Title = "Details";
}
	<div id="main-content">
				<div class="show-posts">
					<div class= "show-posts-header">
						<div class="category-header">
							Tất cả tin rao
						</div>
						<div class="sort-posts">
							<span>Sắp xếp theo:</span>
							<select onchange="if (this.selectedIndex) {location = this.options[this.selectedIndex].value;}">
                                @sortLink("Thông thường", 0);
                                @sortLink("Tiêu đề", 1);
                                @sortLink("Ngày tạo", 2);
                                @sortLink("Lượt xem", 3);
                                @sortLink("Giá", 4);
							</select>
						</div>
					</div> <!--end of show-posts-header-->
                    @foreach (var item in Model) 
                    {
                         <a href="/Post/Details?id=@item.PostId">

                           <div class="post-item">

                               <div class="post-content-wrapper @(item.PostType==1?"vip": "") ">

                                   <div class="post-header">
                                       @item.Title
                                  </div>
                                  <div class="clear"></div>
					                    	<img src="/Content/Upload/Images/@item.Thumbnail" class="post-image"/>
                                   <div class="post-description-wrapper">
                                       <div class="post-content">
                                           @item.ShortDescription
                                       </div>
                                       <div class = "clear"></div>	
                                       <div class="description-i">
								            <span class="description-i-caption">
									            Giá:
								            </span>
								            <span class="description-i-value">
									            @(item.Price==null ? "Thỏa Thuận" : item.Price)
								            </span>
                                        </div><!-- end of description-i -->
                                        <div class="description-i">
								            <span class="description-i-caption">
									            Quận/Huyện:
								            </span>
								            <span class="description-i-value">
									            @item.Zone.ZoneName
								            </span>									
							            </div><!-- end of description-i -->
						            	<!--date-->
							            <span class="published-date">
								            @(item.Created==null? "1/1/2001": item.Created.Value.ToString("dd/MM/yyyy"))
							            </span>


							            
                                   </div><!-- end of post-description-wrapper -->
                               </div><!-- end of post-content-wrapper -->


                            </div> <!--end of postitem-->

                    </a>
                           
                }
        </div> <!--end of show-postsr-->
<div class="pagination">
Trang: @pageLinks()       
</div>
</div> <!--end of main-content-->
		<div class="adswrapper">
			<div class="ads">
					Quảng Cáo
			</div>
		</div>


			<div id="footer" style="margin-left:10px;">	
				"Copyright 2015"
			</div>

WebRaoVat/WebRaoVat/Views/Post/PostManager.cshtml
@{
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}

@model IEnumerable<WebRaoVat.Models.Post>
<h2>Quản lý Các Tin Đăng</h2>

<fieldset>
    <legend>Bộ lọc</legend>
@using (Html.BeginForm("PostManager","Post", FormMethod.Get))
{
    <p> Search: @Html.TextBox("search", ViewBag.searchstring as string) 
        UserName: @Html.TextBox("UserName", ViewBag.UserName as string) 
        Danh Mục: @Html.DropDownList("Category")
        Khu Vực: @Html.DropDownList("Zone")
        Hiển Thị: @Html.DropDownList("IsActive")
        Loại Tin: @Html.DropDownList("PostType")
        Xác nhận: @Html.DropDownList("Approved") 
        Thời Hạn: @Html.DropDownList("Expired")
    <input type="submit" value="Lọc Dữ Liệu" /></p>
}
</fieldset>

<table border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TitleAlias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostCategory.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </th>
 @*       <th>
            @Html.DisplayNameFor(model => model.Detail)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zone.ZoneName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HitCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Thumbnail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Approved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpireDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TitleAlias)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostCategory.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortDescription)
        </td>
@*        <td>
            @Html.DisplayFor(modelItem => item.Detail)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zone.ZoneName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HitCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Thumbnail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Approved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpireDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PostId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PostId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PostId })
        </td>
    </tr>
}

</table>

WebRaoVat/WebRaoVat/Views/Post/Touch.cshtml
@{
    ViewBag.Title = "Touch";
}

<h2>Bạn chỉ có thể đưa tin lên đầu trang sau mỗi 12 tiếng/lần</h2>

<span>
    @Html.ActionLink("Quay lại", "Details", new { id = (int)ViewBag.link_id})
</span>