WebRaoVat/WebRaoVat/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebRaoVat.Models;
using WebMatrix.WebData;
using WebRaoVat.Filters;
using System.Web.Security;


namespace WebRaoVat.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class UserManagerController : Controller
    {
        private raovat_dbEntities db = new raovat_dbEntities();

        //
        // GET: /UserManager/

        public ActionResult Index(string Search, string BusinessExpired, string BanExpired)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 200)
            {
                var ExpiredLst = new List<string>();
                ExpiredLst.Add("All");
                ExpiredLst.Add("Not Yet");
                ExpiredLst.Add("Expired");

                ViewBag.BusinessExpired = new SelectList(ExpiredLst, BusinessExpired);
                ViewBag.BanExpired = new SelectList(ExpiredLst, BanExpired);

                IEnumerable<UserProfile> user = db.UserProfiles;
                if (!String.IsNullOrEmpty(Search))
                    user = user.Where( a => a.Address.Contains(Search)
                                            || a.BannerImage.Contains(Search)
                                            || a.Email.Contains(Search)
                                            || a.Fax.Contains(Search)
                                            || a.FullName.Contains(Search)
                                            || a.HotLine.Contains(Search)
                                            || a.LogoImage.Contains(Search)
                                            || a.Phone.Contains(Search)
                                            || a.Skype.Contains(Search)
                                            || a.Slogan.Contains(Search)
                                            || a.UserName.Contains(Search)
                                            || a.Website.Contains(Search)
                                            || a.Yahoo.Contains(Search)
                                           );

                if (!String.IsNullOrEmpty(BusinessExpired) && BusinessExpired != "All")
                {
                    if (BusinessExpired == "Not Yet")
                        user = user.Where(a => a.BusinessExpireDate.Value < DateTime.Now);
                    else
                        user = user.Where(a => a.BusinessExpireDate.Value > DateTime.Now);
                }

                if (!String.IsNullOrEmpty(BanExpired) && BanExpired != "All")
                {
                    if (BanExpired == "Not Yet")
                        user = user.Where(a => a.UserBanExpireDate.Value < DateTime.Now);
                    else
                        user = user.Where(a => a.UserBanExpireDate.Value > DateTime.Now);
                }
                return View(user.ToList());
            }
            else return HttpNotFound();
        }

        //
        // GET: /UserManager/Details/5

        public ActionResult Details(int id = 0)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 200)
            {
                UserProfile userprofile = db.UserProfiles.Find(id);
                if (userprofile == null)
                {
                    return HttpNotFound();
                }
                return View(userprofile);
            }
            else return HttpNotFound();
        }

        //
        // GET: /UserManager/Create

        public ActionResult Create()
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 200)
            {
                return View();
            }
            else return HttpNotFound();
        }

        //
        // POST: /UserManager/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserProfile userprofile)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 200)
            {
                if (ModelState.IsValid)
                {
                    db.UserProfiles.Add(userprofile);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(userprofile);
            }
            else return HttpNotFound();
        }

        //
        // GET: /UserManager/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 200)
            {
                UserProfile userprofile = db.UserProfiles.Find(id);
                if (userprofile == null)
                {
                    return HttpNotFound();
                }
                return View(userprofile);
            }
            else return HttpNotFound();
        }

        //
        // POST: /UserManager/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile userprofile)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 200)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(userprofile).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(userprofile);
            }
            else return HttpNotFound();
        }

        //
        // GET: /UserManager/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 200)
            {
                UserProfile userprofile = db.UserProfiles.Find(id);
                if (userprofile == null)
                {
                    return HttpNotFound();
                }
                return View(userprofile);
            }
            else return HttpNotFound();
        }

        //
        // POST: /UserManager/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 200)
            {
                UserProfile userprofile = db.UserProfiles.Find(id);
                db.UserProfiles.Remove(userprofile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else return HttpNotFound();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebRaoVat/WebRaoVat/Views/UserManager/Create.cshtml
@{
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}
@model WebRaoVat.Models.UserProfile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserProfile</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FullName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FullName)
            @Html.ValidationMessageFor(model => model.FullName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserType)
            @Html.ValidationMessageFor(model => model.UserType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BannerImage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BannerImage)
            @Html.ValidationMessageFor(model => model.BannerImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fax)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fax)
            @Html.ValidationMessageFor(model => model.Fax)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Review)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Review)
            @Html.ValidationMessageFor(model => model.Review)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rating)
            @Html.ValidationMessageFor(model => model.Rating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Yahoo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Yahoo)
            @Html.ValidationMessageFor(model => model.Yahoo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Skype)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Skype)
            @Html.ValidationMessageFor(model => model.Skype)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HotLine)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HotLine)
            @Html.ValidationMessageFor(model => model.HotLine)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HitCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HitCount)
            @Html.ValidationMessageFor(model => model.HitCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NumPosts)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NumPosts)
            @Html.ValidationMessageFor(model => model.NumPosts)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Slogan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Slogan)
            @Html.ValidationMessageFor(model => model.Slogan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogoImage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogoImage)
            @Html.ValidationMessageFor(model => model.LogoImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserBanExpireDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserBanExpireDate)
            @Html.ValidationMessageFor(model => model.UserBanExpireDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BusinessExpireDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BusinessExpireDate)
            @Html.ValidationMessageFor(model => model.BusinessExpireDate)
        </div>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebRaoVat/WebRaoVat/Views/UserManager/Delete.cshtml
@{
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}
@model WebRaoVat.Models.UserProfile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>UserProfile</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FullName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FullName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BannerImage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BannerImage)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fax)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fax)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Website)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Website)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Review)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Review)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rating)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rating)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Yahoo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Yahoo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Skype)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Skype)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HotLine)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HotLine)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HitCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HitCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NumPosts)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumPosts)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Slogan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Slogan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogoImage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogoImage)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BusinessExpireDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BusinessExpireDate)
    </div>
        <div class="display-label">
         @Html.DisplayNameFor(model => model.UserBanExpireDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserBanExpireDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WebRaoVat/WebRaoVat/Views/UserManager/Details.cshtml
@{
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}
@model WebRaoVat.Models.UserProfile

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>UserProfile</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FullName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FullName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BannerImage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BannerImage)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fax)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fax)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Website)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Website)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Review)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Review)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rating)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rating)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Yahoo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Yahoo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Skype)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Skype)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HotLine)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HotLine)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HitCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HitCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NumPosts)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumPosts)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Slogan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Slogan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogoImage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogoImage)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserBanExpireDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserBanExpireDate)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.BusinessExpireDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BusinessExpireDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebRaoVat/WebRaoVat/Views/UserManager/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}
@model IEnumerable<WebRaoVat.Models.UserProfile>
<h2>Quản lý Thành viên</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

@*int id, string imageurl = null, string imagelink = null, int cateid, bool isvertical, bool expired*@
<fieldset>
    <legend>Bộ lọc</legend>
@using (Html.BeginForm("Index","UserManager", FormMethod.Get))
{
    <p> Search: @Html.TextBox("search", ViewBag.searchstring as string) 
        Doanh nghiệp status: @Html.DropDownList("BusinessExpired")
        User Ban status: @Html.DropDownList("BusinessExpired")
    <input type="submit" value="Lọc Dữ Liệu" /></p>
}
</fieldset>

<table border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BannerImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Review)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Yahoo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Skype)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HotLine)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HitCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumPosts)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Slogan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogoImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessExpireDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserBanExpireDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserType)
        </td>
        <td>
            <img src="/Content/Upload/Images/@item.BannerImage" width="100" height="100"/><br />
            @Html.DisplayFor(modelItem => item.BannerImage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Website)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Review)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Yahoo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Skype)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HotLine)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HitCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumPosts)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Slogan)
        </td>
        <td>
            <img src="/Content/Upload/Images/@item.LogoImage" width="100" height="100"/><br />
            @Html.DisplayFor(modelItem => item.LogoImage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BusinessExpireDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserBanExpireDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>