WebRaoVat/WebRaoVat/Models/UserProfile.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.Posts = new HashSet<Post>();
            this.PostCategories = new HashSet<PostCategory>();
            this.UserAds = new HashSet<UserAd>();
            this.UserWallets = new HashSet<UserWallet>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> UserType { get; set; }
        public string BannerImage { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Review { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string Yahoo { get; set; }
        public string Skype { get; set; }
        public string HotLine { get; set; }
        public Nullable<int> HitCount { get; set; }
        public Nullable<int> NumPosts { get; set; }
        public string Slogan { get; set; }
        public string LogoImage { get; set; }
        public Nullable<System.DateTime> BusinessExpireDate { get; set; }
        public Nullable<System.DateTime> UserBanExpireDate { get; set; }
    
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PostCategory> PostCategories { get; set; }
        public virtual ICollection<UserAd> UserAds { get; set; }
        public virtual ICollection<UserWallet> UserWallets { get; set; }
    }
}

WebRaoVat/WebRaoVat/Controllers/UserAdController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebRaoVat.Models;
using WebMatrix.WebData;
using WebRaoVat.Filters;
using System.Web.Security;

namespace WebRaoVat.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class UserAdController : Controller
    {
        private raovat_dbEntities db = new raovat_dbEntities();

        //
        // GET: /UserAd/

        public ActionResult Index()
        {
            var userads = db.UserAds.Where( u => u.UserId == WebSecurity.CurrentUserId).Include(u => u.UserProfile);
            return View(userads.ToList());
        }

        //
        // GET: /UserAd/UserAdManager

        public ActionResult UserAdManager(string Search, string Approved)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 100)
            {
                var ApprovedLst = new List<string>();
                ApprovedLst.Add("All");
                ApprovedLst.Add("Chưa kiểm duyệt");
                ApprovedLst.Add("Đã kiểm duyệt");

                ViewBag.Approved = new SelectList(ApprovedLst, Approved);
                var userads = db.UserAds.Include(u => u.UserProfile);
                if (!String.IsNullOrEmpty(Search))
                    userads = userads.Where(a => a.ImageURL.Contains(Search)
                                            || a.ImageLink.Contains(Search)
                                           );
                if (!String.IsNullOrEmpty(Approved) && Approved != "All")
                {
                    userads = userads.Where(a => a.Approved == ((Approved == "Đã kiểm duyệt") ? true : false));
                }

                ViewBag.searchstring = Search;
                return View(userads.ToList());
            }
            else return HttpNotFound();
        }

        //
        // GET: /UserAd/Details/5

        public ActionResult Details(int id = 0)
        {
            UserAd userad = db.UserAds.Find(id);
            if (userad == null)
            {
                return HttpNotFound();
            }
            return View(userad);
        }

        //
        // GET: /UserAd/Create

        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.UserProfiles.Where(u => u.UserId == WebSecurity.CurrentUserId), "UserId", "UserName");
            return View();
        }

        //
        // POST: /UserAd/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserAd userad)
        {
            string[] images_links = null;
            if (Request["images"] != null)
                images_links = Request["images"].ToString().Split(':');
//               if (ModelState.IsValid)
//                {
                if (images_links.Length == 1)
                {
                    if (!String.IsNullOrEmpty(images_links[0]))
                        userad.ImageURL = images_links[0];
                    else
                        userad.ImageURL = "NoImage.jpg";
                }
                else
                    userad.ImageURL = "NoImage.jpg";
                userad.UserId = WebSecurity.CurrentUserId;
                db.UserAds.Add(userad);
                db.SaveChanges();
                return RedirectToAction("Index");
//            }
//
//            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", userad.UserId);
//            return View(userad);
        }

        //
        // GET: /UserAd/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserAd userad = db.UserAds.Find(id);
            ViewBag.EditableApproved = 0;
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) != null && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 100)
            {
                ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", userad.UserId);
                ViewBag.EditableApproved = 1;
                return View(userad);
            }
            if (userad == null || userad.UserId != WebSecurity.CurrentUserId)
            {
                return HttpNotFound();
            }
            
            ViewBag.UserId = new SelectList(db.UserProfiles.Where(u => u.UserId == WebSecurity.CurrentUserId), "UserId", "UserName", userad.UserId);
            return View(userad);
        }

        //
        // POST: /UserAd/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserAd userad)
        {
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) == null)
                return HttpNotFound();
            if (userad == null || (userad.UserId != WebSecurity.CurrentUserId && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType <= 100))
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                db.Entry(userad).State = EntityState.Modified;
                db.SaveChanges();
                if (db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType > 100)
                    return RedirectToAction("UserAdManager");
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserProfiles.Where(u => u.UserId == WebSecurity.CurrentUserId), "UserId", "UserName", userad.UserId);
            return View(userad);
        }

        //
        // GET: /UserAd/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserAd userad = db.UserAds.Find(id);
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) == null)
                return HttpNotFound();
            if (userad == null || (userad.UserId != WebSecurity.CurrentUserId && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType <= 100))
            {
                return HttpNotFound();
            }
            return View(userad);
        }

        //
        // POST: /UserAd/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserAd userad = db.UserAds.Find(id);
            if (db.UserProfiles.Find(WebSecurity.CurrentUserId) == null)
                return HttpNotFound();
            if (userad == null || (userad.UserId != WebSecurity.CurrentUserId && db.UserProfiles.Find(WebSecurity.CurrentUserId).UserType <= 100))
            {
                return HttpNotFound();
            }
            FileController a = new FileController();
            a.Delete1(userad.ImageURL);
            db.UserAds.Remove(userad);            
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebRaoVat/WebRaoVat/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using WebMatrix.WebData;
using System.Web.Mvc;
using WebRaoVat.Models;
using WebRaoVat.Filters;

namespace WebRaoVat.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class UserProfileController : Controller
    {
        private raovat_dbEntities db = new raovat_dbEntities();

        //
        // GET: /UserProfile/5

        public ActionResult Index()
        {
            int CurrentId = WebSecurity.CurrentUserId; // >=0 if exist; -1 if anonymous user

            return RedirectToAction("Details");
            
        }

        //
        // GET: /UserProfile/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = -1, int page = 1, int PageSize = 5)
        {
            if(id<0)
                id = WebSecurity.CurrentUserId;
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            db.Entry(userprofile).State = EntityState.Modified;
            userprofile.HitCount = ((userprofile.HitCount != null) ? userprofile.HitCount + 1 : 1);
            db.SaveChanges();

            ViewBag.CurrentPage = page;
            ViewBag.PageSize = PageSize;
            ViewBag.id = id;
            ViewBag.TotalPages = (int)Math.Ceiling((double)userprofile.Posts.Count() / PageSize);
            userprofile.Posts = userprofile.Posts.Skip((page - 1) * PageSize).Take(PageSize).ToList();

            var Ads = db.UserAds.Where(p => p.UserId == id);
            Ads = Ads.Where(p => p.Approved == true);
            ViewBag.UserAds = "none";
            if (Ads != null)
            {
                ViewBag.UserAds = Ads.OrderBy(p => p.ImageOdr).ToList();
            }

            return View(userprofile);
        }

        //User profile is created in AccountController, no need for recreating here
        //
        // GET: /UserProfile/Create
/*
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /UserProfile/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userprofile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userprofile);
        }
*/
        // upgrade user, can be done with admin or user
        // GET: /UserProfile/Upgrade/
        public ActionResult Upgrade(int id =-1)
        {
            if(id<0)
                id = WebSecurity.CurrentUserId;
            
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
                return HttpNotFound();
            userprofile.UserType = (int) UserType.DoanhNghiep; //0: canhan, 1 doanh nghiep
            db.Entry(userprofile).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Edit");
        }



        //
        // GET: /UserProfile/Edit/

        public ActionResult Edit()
        {
            int id = WebSecurity.CurrentUserId;
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
        /*      if (userprofile.UserType == UserType.KhachHangCaNhan.ToString())
                  ViewBag.UserType=userprofile.UserType
              else
                  return DoanhNghiep(userprofile);*/
              List<string> ImagesCollection = new List<string>();
              ImagesCollection.Add(userprofile.LogoImage);
              ImagesCollection.Add(userprofile.BannerImage);
              ViewBag.Images = ImagesCollection.ToArray();
              return View(userprofile);
        }

        //
        // POST: /UserProfile/Edit/

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile userprofile)
        {
            int CurrentId = WebSecurity.CurrentUserId;
            if (CurrentId != userprofile.UserId)
               return HttpNotFound();

            string[] images_links = null;
            if (Request["images"] != null)
                images_links = Request["images"].ToString().Split(':');
/* Check valid by javascript client side. better than this one
            if (ModelState.IsValid)
            {
            */
            if (images_links.Length ==2)
            {
                if (!String.IsNullOrEmpty(images_links[0]))
                    userprofile.LogoImage = images_links[0];
                else
                    userprofile.LogoImage = "NoImage.jpg";

                if (!String.IsNullOrEmpty(images_links[1]))
                    userprofile.BannerImage = images_links[1];
                else
                    userprofile.BannerImage = "NoImage.jpg";
            }
            else if (images_links.Length == 1)
            {
                if (!String.IsNullOrEmpty(images_links[0]))
                    userprofile.LogoImage = images_links[0];
                else
                    userprofile.LogoImage = "NoImage.jpg";
            }

                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
              //  return HttpNotFound();
                return RedirectToAction("Details");
  /*          }

            return View(userprofile);*/
        }
/*
        //
        // GET: /UserProfile/Delete/5

        public ActionResult Delete(int id = 0)
        {
            id = WebSecurity.CurrentUserId;

            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /UserProfile/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        */
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        public enum UserType
        {
            KhachHangCaNhan,
            DoanhNghiep
        }
    }
}

WebRaoVat/WebRaoVat/Views/UserProfile/Create.cshtml
@model WebRaoVat.Models.UserProfile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserProfile</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FullName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FullName)
            @Html.ValidationMessageFor(model => model.FullName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserType)
            @Html.ValidationMessageFor(model => model.UserType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BannerImage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BannerImage)
            @Html.ValidationMessageFor(model => model.BannerImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fax)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fax)
            @Html.ValidationMessageFor(model => model.Fax)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Review)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Review)
            @Html.ValidationMessageFor(model => model.Review)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rating)
            @Html.ValidationMessageFor(model => model.Rating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Yahoo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Yahoo)
            @Html.ValidationMessageFor(model => model.Yahoo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Skype)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Skype)
            @Html.ValidationMessageFor(model => model.Skype)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HotLine)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HotLine)
            @Html.ValidationMessageFor(model => model.HotLine)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HitCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HitCount)
            @Html.ValidationMessageFor(model => model.HitCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NumPosts)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NumPosts)
            @Html.ValidationMessageFor(model => model.NumPosts)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Slogan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Slogan)
            @Html.ValidationMessageFor(model => model.Slogan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogoImage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogoImage)
            @Html.ValidationMessageFor(model => model.LogoImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomAds)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomAds)
            @Html.ValidationMessageFor(model => model.CustomAds)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebRaoVat/WebRaoVat/Views/UserProfile/Edit.cshtml
@model WebRaoVat.Models.UserProfile

<fieldset>
    <legend style="font-size:150%;">Chức năng</legend>
    @if (Model.UserType > 200)
    {
        <span style="background-color:aquamarine; font-size: large">
            @Html.ActionLink("Bảng điều khiển Administrator","Index","AdministratorDashboard")
        </span>
    }
    else if (Model.UserType > 100)
    {
        <span style="background-color:azure; font-size: large">
            @Html.ActionLink("Bảng điều khiển Moderator", "Index", "ModeratorDashboard")
        </span>
    }
    <span style="background-color:greenyellow; font-size: large">
            @Html.ActionLink("Các mục đánh dấu", "Index", "UserBookmark")
    </span>
    <span style="background-color:bisque; font-size: large">
            @Html.ActionLink("Thay đổi mật khẩu", "ChangePassword", "Account")
    </span>
</fieldset>
<br />
<fieldset>
@if(Model.UserType==(int)0) //khach hang ca nhan
{ //usual form

<div class="upgrade-button">
            <a href="/UserProfile/Upgrade"> Nâng cấp lên khách hàng doanh nghiệp</a>
</div>
<legend style="font-size:150%;">Chỉnh sửa thông tin cá nhân</legend>
<form  id="UserEdit" class="aspform" action="/userprofile/edit" method="post" novalidate="novalidate">
 
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.UserName)
        @Html.HiddenFor(model => model.UserType)
 
        <br /> Tên đầy đủ <br />
        <div class="editor-field">
            @Html.EditorFor(model => model.FullName)
            @Html.ValidationMessageFor(model => model.FullName)
        </div>
        <br />
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <br />Số điện thoại: <br />
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>
        <br />
        <p>
            <input type="submit" value="Lưu thay đổi" />
        </p>
   </form>  
}
else{ //khach hang doanh nghiep, nhieu field hon
<span style="background-color:blueviolet; font-size: large">
     @Html.ActionLink("Đăng quảng cáo trên trang doanh nghiệp", "Index", "UserAd")
</span>
<span style="background-color:orchid; font-size: large">
     @Html.ActionLink("Đến trang doanh nghiệp của bạn", "Details", "UserProfile", new { id = Model.UserId}, null)
</span>
<legend style="font-size:150%;">Chỉnh sửa thông tin doanh nghiệp</legend>
<form  id="UserEdit" class="aspform" action="/userprofile/edit" method="post" novalidate="novalidate">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.UserName)
        @Html.HiddenFor(model => model.UserType)
@*
        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>
*@
        <br /> Tên Công Ty <br />
        <div class="editor-field">
            @Html.EditorFor(model => model.FullName)
            @Html.ValidationMessageFor(model => model.FullName)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        

        <input type="hidden" value="@Model.UserType" />
@*
        <div class="editor-label">
            @Html.LabelFor(model => model.BannerImage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BannerImage)
            @Html.ValidationMessageFor(model => model.BannerImage)
        </div>
*@
        <br /> Địa chỉ <br />
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fax)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fax)
            @Html.ValidationMessageFor(model => model.Fax)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Yahoo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Yahoo)
            @Html.ValidationMessageFor(model => model.Yahoo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Skype)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Skype)
            @Html.ValidationMessageFor(model => model.Skype)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HotLine)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HotLine)
            @Html.ValidationMessageFor(model => model.HotLine)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Slogan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Slogan)
            @Html.ValidationMessageFor(model => model.Slogan)
        </div>
@*
        <br /> Hình logo <br />
        <div class="editor-field">
            @Html.EditorFor(model => model.LogoImage)
            @Html.ValidationMessageFor(model => model.LogoImage)
        </div>
    *@
        <p></p>
        <p></p>
        <p>
            <input type="submit" value="Lưu thay đổi" />
        </p>
    </form>
}

<form action="/File/Upload" class ="dropzone" id="UploadImage">
    <h3> Upload hình ảnh, chọn theo thứ tự: </h3>
		<ul>
			<li>Logo(vuông, nhỏ)</li>
			<li>Hình banner (lớn)</li>
		</ul>
</form>
@{
                string form_id = "UploadImage";
                string form_contain_fields_id = "UserEdit";
                int num_images = 2;
}

    @if (ViewBag.Images != null)
    {
        @ViewsUtilities.EditFile(form_id, form_contain_fields_id, num_images, ViewBag.Images);
    }
    else
    {
        @ViewsUtilities.Upload_File(form_id, form_contain_fields_id, num_images);
    }

</fieldset>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}